platform :ios,'8.0'
inhibit_all_warnings!

target "FMBaseProject" do
  pod 'MBProgressHUD', '~> 0.9.2'
  pod 'RETableViewManager', '1.6'
  pod 'MJRefresh', '~> 3.1.0'
  pod 'YYKeyboardManager'
  pod 'SDWebImage'
  pod 'TZImagePickerController', '~> 1.5.0'
  pod 'AFNetworking', '~> 3.0.4'
end
